### ISSUE TITLE
Is there built in way to get the coefficients on the covariates?

### ISSUE THREAD

**Issue by achenzion** [ddimmery/rdd#2]
This package is awesome! I was wondering if there was any built in ability to get the coefficients (and standard errors) from the covariates.

**Comment by ddimmery** [comment]
Thanks! Sorry for the delayed response.

Covariates do not have a causal interpretation, of course, but if you return the entire model object, you can examine what the estimated coefficients are. (e.g. rd <- RDestimate(y~d | x1 + x2,df,model=TRUE); summary(rd$model[[1]]) will return model based coefs + standard errors ). This functionality is really for diagnostic purposes only, though.
